// This file is generated by AutoRefl

#include <UDP/Reflection/Reflection.h>

namespace Ubpa::AutoRefl {
	void Register_Ubpa_Cmpt() {
		Reflection<Ubpa::Cmpt>::Instance()
			.Register("meta0", "a")
			.Register("meta1", "")
			.Register(&Ubpa::Cmpt::x, "x")
			.Register("x", "meta2", "c")
			;
	}
}
